server:
  port: 9000

spring:
  flyway:
    enabled: true
  datasource:
    url:  jdbc:postgresql://localhost:5432/Users
    username: lalith
    password: 2004
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true